port: 3005
commercetools:
  projectKey: flaschenpost-development
  authHost: https://auth.europe-west1.gcp.commercetools.com
  apiHost: https://api.europe-west1.gcp.commercetools.com
  clientId: SV4jAYRjtyKJPXT1JYJTlBSo
  clientSecret: 7EMXcWyFsvgdxjmwopKrYCwzi27BOl01